server:
  host: "0.0.0.0"
  port: ":25565"
  debug: false #Wanna see the juicy info?
  timeout: 15 #In seconds
  multicore: true
  SO_REUSE: true
  send-buffer: 64
  recv-buffer: 64
  read-buffer-cap: 64
  net-event-loop: 8
  protocol:
    AvailableProtocols: []
    block-players-on-login: true
performance: #Change me!
   cpu: 8
   gc-percent: 100
   view-distance: 12
   simulation-distance: 12