server:
  host: "127.0.0.1" #currently doesn't do shit
  port: ":25565" #Set the port
  debug: true #Wanna see the juicy info?
  timeout: 15 #In seconds
performance: #Change me!
   cpu: 4
   gc-player-interval: 15
   gc-percent: 200
