server:
  host: "127.0.0.1" #currently doesn't do shit
  port: ":25570" #Set the port
  debug: true #Wanna see the juicy info?
  timeout: 15 #In seconds
  protocol:
    AvailableProtocols: []
    block-players-on-login: true
performance: #Change me!
   cpu: 8
   enable-gc-player: true
   gc-player-interval: 15
   gc-percent: 200
debug-opts:
    packet-anal: false #switches HoneyGO into a MITM proxy that captures and decodes packets
    packet-anal-address: "192.168.0.42:25580" #Server address that HoneyGO probes
    maintenance: true
