name: HoneyGO

on:
  push:
    branches:
      - main
      - dev/net
      - dev/nbt
  pull_request:
    branches:
      - main
      - dev/net
      - dev/nbt
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.6

    - name: Tidy
      run: go mod tidy
      
    - name: BuildLinux
      run: go build -o ~/HoneyGO-Linux/ -v ./...
      
    - name: BuildWindows
      run: env GOOS=windows GOARCH=amd64 go build -o ~/HoneyGO-Windows/ -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Upload Linux Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: HoneyGO-Linux # optional, default is artifact
         # A file, directory or wildcard pattern that describes what to upload
        path: ~/HoneyGO-Linux/HoneyGO
        if-no-files-found: error
        
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: HoneyGO-Windows # optional, default is artifact
         # A file, directory or wildcard pattern that describes what to upload
        path: ~/HoneyGO-Windows/HoneyGO.exe
        if-no-files-found: error
